# Generated by Django 4.0.1 on 2022-01-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='PUT_EMAIL',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
