# Generated by Django 4.0.1 on 2022-01-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_put_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='PUT_EMAIL',
            new_name='EMAIL',
        ),
    ]
