# Generated by Django 4.0.1 on 2022-01-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_rename_put_email_link_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='SET_PRICE',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
